name: TestMain
version: 1.0.0

detections:
  - name: "detection_png"
    mimetype: "image/png"
  - name: "detection_pdf_older_than_30_days"
    mimetype: "application/pdf"
    max_age: 30
  - name: "detection_yara"
    yara_rules_dir: "./detection/checkyara/yararules"


recursions:
  - name: "recursion1"
    path: "../"
    max_depth: 10 

logs:
  - name: "logging1"
    log_format: "json"
    log_repository: "./.log"

actions:
  - name: "action1"
    delete: false 
    log: "logging1"

rules:
  - name: "FINALRULE1"
    action: "action1"
    detection: ["detection_png", "detection_pdf_older_than_30_days", "detection_yara"]
    recursion: "recursion1"
