name: Lint and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.1  # ou ta version exacte dans go.mod

      - name: Check code formatting (gofmt)
        run: |
          UNFORMATTED=$(gofmt -l .)
          if [ -n "$UNFORMATTED" ]; then
            echo "❌ Code non formaté:"
            echo "$UNFORMATTED"
            exit 1
          fi
          echo "✅ Code bien formaté"

      - name: Run tests
        run: go test -v

